# defaultEntryPoints must be at the top because it should not be in any table below
# Initial from:
# https://github.com/containerize-my-server/reverse-proxy/blob/master/traefik.toml
defaultEntryPoints = ["http", "https"]


# Entrypoints, http and https
[entryPoints]

# http should be redirected to https
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "just@justobjects.nl"
storage = "/acme.json"
entryPoint = "https"
onHostRule = false
onDemand = false

[acme.tlsChallenge] #enables the TLS ALPN Challenge

[[acme.domains]]
  main = "sta.map5.nl"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "sta.map5.nl"
watch = true
exposedbydefault = false

[accessLog]
  filePath = "/var/log/traefik/access.log"
