- name: "Start/Stop Service"
  hosts: all
  gather_facts: yes

  vars_files:
    - vars/vars.yml

  tasks:
    - name: "stop"
      shell: "service stademo stop; docker ps"
      tags: stop

    - name: "start"
      shell: "service stademo start; docker ps"
      tags: start

    - name: "status"
      shell: "service stademo status; docker ps"
      tags: status

    # https://docs.ansible.com/ansible/latest/modules/reboot_module.html
    - name: "Reboot"
      shell: "shutdown -r now"
      tags: reboot
