version: '2'
services:

#    node-red:
#        # image: nodered/node-red-docker:slim-v8
#        image: nodered/node-red-docker:latest
#        volumes:
#            - nodered:/data
#        ports:
#            - "1880:1880"

    # MQTT Broker
    mosquitto:
        image: toke/mosquitto
        volumes:
            - mosquitto_data:/mqtt/data
            - mosquitto_conf:/mqtt/config:ro
        ports:
            - "1883:1883"
            - "9001:9001"

    # SensorThings API DB
    gost-db:
        image: geodan/gost-db
        volumes:
            - postgis:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: gost
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

    # SensorThings API Server
    gost:
        image: geodan/gost
        volumes:
            - gost_conf:/gostserver/config
        depends_on:
            - mosquitto
            - gost-db
        environment:
            GOST_DB_HOST: gost-db
            GOST_MQTT_HOST: mosquitto

    # SensorThings Dashboard
    dashboard:
        image: geodan/gost-dashboard
        ports:
            - "8080:8080"
        depends_on:
            - gost
volumes:
    postgis: {}
    nodered: {}
    gost_conf: {}
    mosquitto_data: {}
    mosquitto_conf: {}
