version: "3"
services:

    # MQTT Broker
    mosquitto:
        image: toke/mosquitto

        container_name: mosquitto

        volumes:
            - mosquitto_data:/mqtt/data
            - mosquitto_conf:/mqtt/config:ro

        ports:
            - "1883:1883"
            - "9001:9001"

    # SensorThings API DB
    gost-db:
        image: geodan/gost-db

        container_name: gost-db

        volumes:
            - postgis:/var/lib/postgresql/data

        env_file:
            - postgres.env

    # SensorThings API Server
    gost:
        image: geodan/gost

        container_name: gost

        volumes:
            - ./gost-config.yaml:/app/config.yaml

        depends_on:
            - mosquitto
            - gost-db

#        ports:
#            - "80:8080"
        labels:
            - "traefik.backend=gost"
            - "traefik.enable=true"
            - "traefik.frontend.priority=5"
            - "traefik.frontend.rule=Host:sta.map5.nl; PathPrefixStrip:/gost"
            - "traefik.docker.network=stademo-network"
            - "traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*"
            
    # SensorThings Dashboard
    dashboard:
        image: geodan/gost-dashboard

        container_name: gost-dashboard

#        labels:
#            - "traefik.backend=gostdashboard"
#            - "traefik.enable=true"
#            - "traefik.port=8080"
#            - "traefik.frontend.priority=5"
#            - "traefik.frontend.rule=Host:sta.map5.nl; PathPrefixStrip:/dashgost"
#            - "traefik.docker.network=stademo-network"
        ports:
            - "8080:8080"

        depends_on:
            - gost

volumes:
    postgis: {}
    mosquitto_data: {}
    mosquitto_conf: {}

networks:
    default:
        external:
            name: stademo-network

