server:
    name: Geonovum GOST Server
    host:
    port: 8080
    externalUri: https://sta.map5.nl/gost
    maxEntityResponse: 20
    indentedJson: true
    https: false
    httpsCert:
    httpsKey:
database:
    host: gost-db
    port: 5432
    user: postgres
    password: postgres
    database: gost
    schema: v1
    ssl: false
    maxIdleConns: 30
    maxOpenConns: 100
mqtt:
    enabled: true
    verbose: true
    host: moquitto
    port: 1883
    prefix: GOST
    clientId: gost
    subscriptionQos: 1
    persistent: true
    order: true
    ssl: false
    caCertFile:
    clientCertFile:
    privateKeyFile:
    keepAliveSec: 300
    pingTimeoutSec: 20
logger:
    fileName:
    verbose: true
